{
 "title": "Mongonaut Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(container_spec_cpu_shares{container!~\".*POD.*\", container=~\".*mongonaut.*\"})",
     "legendFormat": "max cpu"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"mongonaut\"}[5m])) by (container, pod)",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name=~\".*k8s_mongonaut_mongonaut.*\", name!~\".*POD.*\"}) by (pod) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".*mongonaut.*\"}[5m])) by (pod_name)",
     "legendFormat": "RX {{pod_name}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".*mongonaut.*\"}[5m])) by (pod_name)",
     "legendFormat": "TX {{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name=\"mongonaut\"}) by (container_name) / sum(label_join(kube_pod_container_resource_limits_memory_bytes,\"container_name\", \"\", \"container\")) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Total number of alarms api calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=\"/mongonaut/alarms\", method=\"GET\"}) by (uri, method)",
     "legendFormat": "{{method}} {{uri}}"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{uri=\"/mongonaut/alarms\", method=\"POST\"}) by (uri, method)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}